`environment.yml`
```yaml
name: ml-adsorption
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - openpyxl
  - joblib
  - matplotlib
  - seaborn
  - shap
  - pip
